modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "roughlyenoughresources"
version = "${version}"
displayName = "Roughly Enough Resources"
authors = "shedaniel"
description = '''
This mod extends Just Enough Items to show you at what heights in the world you can find various blocks.
'''
#logoFile = ""

[[dependencies.roughlyenoughresources]]
modId = "neoforge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughresources]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughresources]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"